### ISSUE TITLE
[bug] ball machine not saving settings

### ISSUE THREAD

**Issue by carrotstien** [ForFunLabs/ElevenPublicBugsAndAsks#215]

**Comment by ab050505** [comment]
also, not sure if its supposed to have been fixed yet but the following issue is still there (things seem to have become a bit more erratic actually (the "seconds per launch spread" setting seems to get set to some non-zero value automatically at times (think it happens when we try to change "seconds per launch" but did not check it thoroughly)):

![image](https://user-images.githubusercontent.com/28642046/70357163-3f0cf500-189c-11ea-94fa-b5a813acb039.png)

**Comment by ab050505** [comment]
![image](https://user-images.githubusercontent.com/28642046/70357278-84312700-189c-11ea-9a6a-ff1280e30d05.png)

**Comment by ab050505** [comment]
https://streamable.com/1f1dt
the erratic behavior can be seen in the above video. steps:
1) launch ball machine mini game 
2) change the "seconds per launch spread" setting to some non-zero value
3) change it back to zero
4) move the cursor over the # symbol (lower left corner of ball machine settings). this causes the "seconds per launch spread" setting to change to some non-zero value (this also happens if we move the cursor over the "seconds per launch spread" setting from the right (and may be with other such cursor movements as well))

(I am not pressing any buttons on either of the controllers while moving the cursor)
(this behavior seems to be occurring only on rift/pc and not on quest)

**Comment by carrotstien** [comment]
i've put in a fix for this, pending deployment

regarding saving, it's working on pc unity, but i'll verify that it works on quest/build proper before closing

**Comment by carrotstien** [comment]
should be fixed now
