### ISSUE TITLE
[issue] "friend requests" and "match requests" buttons don't seem to be working properly

### ISSUE THREAD

**Issue by ab050505** [ForFunLabs/ElevenPublicBugsAndAsks#240]
in the following screen, notifications shows some pending match requests. but clicking on "friend requests" and "match requests" results in empty lists. i thought may be the notifications list shows everything and these two buttons act as filters. but clicking on "match requests" is not showing the pending match requests that are shown under notifications. the other possibility is that friend requests and match requests are supposed to show the friend/match requests that we have sent out. but clicking on friend requests is not showing the two friend requests which i sent out a few minutes earlier. 

![image](https://user-images.githubusercontent.com/28642046/71844575-744f7180-30ec-11ea-927a-89b6768bc327.png)

**Comment by carrotstien** [comment]
yea this is a known issue. The notifications button is currently showing you all requests you haven't acted on, including ones you missed. While the other two show you ones you can act on. 
We need to change it so that the first button only shows you ones you can act on right now. There should never be a point to default the user to see things they can't do much with except 'delete' or 'mark as read'

...that should be reserved to some out of the way "notification history" button

**Comment by carrotstien** [comment]
changed the order of the buttons, and will be updating the notifications button to say "history"

**Comment by carrotstien** [comment]
changed the order of the buttons, and will be updating the notifications button to say "history"
