### ISSUE TITLE
ball spawn issues in mp

### ISSUE THREAD

**Issue by carrotstien** [ForFunLabs/ElevenPublicBugsAndAsks#244]
no no
cant even spawn it
I mean before we select ranked/unranked we can spawn and play both
when we start the game none of us can spawn the ball
I mean we click the trigger to spawn and no ball nothing
tried restart game both of us but nothing

**Comment by ab050505** [comment]
seemed to happen with toelessfoot now.
video:
https://streamable.com/inaw6
(btw, the "ball reset event" message appearing at the net without the person recording the video not doing anything seems to actually be because the player on the other side is doing the reset from their side (rather than happening on its own))
logs:
https://drive.google.com/file/d/1NQuic3rZSxNA0NfXE2-Ax78F_OkMXRtb/view?usp=sharing

**Comment by carrotstien** [comment]
has this happened recently? I have been looking through some log and haven't seen any

**Comment by dukeoflegs** [comment]
Closing, no longer an issue.
