### ISSUE TITLE
point bug MP regarding the net

### ISSUE THREAD

**Issue by carrotstien** [ForFunLabs/ElevenPublicBugsAndAsks#247]
1. Multiple times, I've seen a situation where (usually my opponent) hits the ball into the net and the point is over and scored as a loss to them, but hits the still-existant ball again (by accident or out of frustration) and the game scores them a further lost point. Also sometimes messes up the next point (in the most recent case, insta-faulting my valid serve in the next point).

**Comment by carrotstien** [comment]
StownieDazeToday at 12:39 AM
yeah #1 has happened to me as well. cant exactly remember the series of events but from what i can remember it generally hits the net, drops down and bounces on the table a couple of times, opponent hits the ball off the table (to the side) & another point gets counted

**Comment by Llamalland** [comment]
I *think* this happens most often when the person who hits the ball and loses the point is set to receive for the next point. That could be some kind of significance bias, though, I might be noticing it more because it robs me of a serve. Doesn't seem like it would make a difference, but maybe? In case something is missing when you test this.

**Comment by carrotstien** [comment]
i am pretty sure this is fixed, closing until further incident
