### ISSUE TITLE
[Quest][Bug][0.4.0] App can't start with an avatar who wears glasses.

### ISSUE THREAD

**Issue by drive1600** [ForFunLabs/ElevenPublicBugsAndAsks#59]
Create avater who wears glasses makes app crash on start-up. No problem without eyewere and noproblem with vr-hmd style eyewears.

**Comment by carrotstien** [comment]
ooo interesting. Can you please tail the logs from start of application
using ADB - and then send them to me.

"adb logcat -s Unity > log.txt"

if you can't do it, i'll push in a change to display the avatar id (which
is what i need), so i can replicate and fix on my side.

**Comment by drive1600** [comment]
Ok! I will try.

**Comment by GeneralFailure-ch** [comment]
Put up a video: https://drive.google.com/drive/folders/1lVhjcg_Lf8EwSYnM6OHb9ip0nUTpVplK
Beta_Behind Head.mp4
Where the Avatar coincidentally has Glasses (worked normal). Might depend on the kind of Glasses.

Actually I wanted to show in the video, the AI playing with the paddle behind the Head (i guess this is because the AI does not do backhands -> which already is a depending Topic here) and also after that, an wonderfull example for the magnuss effect  (i guess its that). Which just looks and plays beautifull!

**Comment by drive1600** [comment]
Hello, thank you for additional test.
> Might depend on the kind of Glasses.

Yes, I found it happened with frameless type glasses (shown at just under plain eyeware-less head).
I am verry sorry to I wrote was not enough.

**Comment by carrotstien** [comment]
fixed as of v 0.33.0
